### ISSUE TITLE
Documentation or possible syntax error

### ISSUE THREAD

**Issue by docfate111** [remiliacn/ASU-Class-Search#1]
Hello. I am trying to make an API for my college and in line 80 under retrieve_rmp_info() shouldn't the URL be ``` url = "https://www.ratemyprofessors.com/search.jsp?queryoption=HEADER&queryBy=teacherName" \
                  "&schoolName=%s" \
                  "&schoolID=%s&query=%s" % ('+'.join(self.schoolName.split(' ')), str(self.school_id), '+'.join(self.teacher_name.split(' ')))```
Before it was ``` self.schoolId+self.teachername ``` which gives an error from adding an int to string

**Comment by wongcoder** [comment]
Wow... fastest response to issue I've ever seen.. +1 to this creator...
